import request from "supertest";
import mongoose from "mongoose";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import { MongoMemoryServer } from "mongodb-memory-server";
import app from "../src/app";
import { Claim } from "../src/models/Claim";
import { Policy } from "../src/models/Policy";
import { User } from "../src/models/User";

describe("API integration tests", () => {
  let mongoServer: MongoMemoryServer;

  // Start an isolated in-memory MongoDB instance for this test suite.
  beforeAll(async () => {
    mongoServer = await MongoMemoryServer.create();
    await mongoose.connect(mongoServer.getUri());
  });

  // Close database resources after all tests complete.
  afterAll(async () => {
    await mongoose.connection.close();
    await mongoServer.stop();
  });

  // Reset collections before each test so cases stay independent.
  beforeEach(async () => {
    await Promise.all([
      User.deleteMany({}),
      Policy.deleteMany({}),
      Claim.deleteMany({})
    ]);

    await mongoose.connection.collection("counters").deleteMany({});
  });

  // Verifies successful registration returns HTTP 201 and a JWT token payload.
  it("Auth: register returns a token", async () => {
    const email = `register.${Date.now()}@example.com`;

    const response = await request(app).post("/api/auth/register").send({
      name: "Test User",
      email,
      password: "password123"
    });

    expect(response.status).toBe(201);
    expect(response.body.token).toBeTruthy();
    expect(response.body.user.email).toBe(email);
  });

  // Verifies invalid credentials are rejected with HTTP 401.
  it("Auth: login with wrong password returns 401", async () => {
    const email = `login.${Date.now()}@example.com`;

    // First create a real account, then attempt login with a bad password.
    await request(app).post("/api/auth/register").send({
      name: "Login User",
      email,
      password: "password123"
    });

    const response = await request(app).post("/api/auth/login").send({
      email,
      password: "wrongpass123"
    });

    expect(response.status).toBe(401);
  });

  // Verifies policy numbers are generated by policy type when not provided by client.
  it("Policies: create policy returns generated policy number", async () => {
    const email = `policy.${Date.now()}@example.com`;

    const registerResponse = await request(app).post("/api/auth/register").send({
      name: "Policy User",
      email,
      password: "password123"
    });

    const token = registerResponse.body.token as string;

    const response = await request(app)
      .post("/api/policies")
      .set("Authorization", `Bearer ${token}`)
      .send({
        holderName: "Generated Policy Holder",
        type: "home",
        premium: 1800,
        status: "active",
        effectiveDate: "2026-01-01",
        expirationDate: "2027-01-01"
      });

    expect(response.status).toBe(201);
    expect(response.body.policyNumber).toMatch(/^POL-HOME-\d+$/);
  });

  // Verifies an authenticated user can create a claim when required fields are present.
  it("Claims: create a claim returns 201", async () => {
    const email = `claim.${Date.now()}@example.com`;

    // Register user and capture JWT for authorized claim creation.
    const registerResponse = await request(app).post("/api/auth/register").send({
      name: "Claim User",
      email,
      password: "password123"
    });

    const token = registerResponse.body.token as string;
    const userId = registerResponse.body.user.id as string;

    // Create a policy first because claims require a valid policy reference.
    const policy = await Policy.create({
      policyNumber: `POL-${Date.now()}`,
      holderName: "Policy Holder",
      type: "auto",
      premium: 1200,
      status: "active",
      effectiveDate: new Date("2026-01-01"),
      expirationDate: new Date("2027-01-01"),
      owner: userId
    });

    const response = await request(app)
      .post("/api/claims")
      .set("Authorization", `Bearer ${token}`)
      .send({
        policy: policy.id,
        description: "Rear-end collision",
        incidentDate: "2026-08-01",
        amount: 2500
      });

    expect(response.status).toBe(201);
    expect(response.body.policy).toBeTruthy();
    expect(response.body.description).toBe("Rear-end collision");
  });

  // Verifies protected claim routes enforce authentication.
  it("Claims: get claims without auth returns 401", async () => {
    const response = await request(app).get("/api/claims");

    expect(response.status).toBe(401);
  });

  // Verifies request validation returns HTTP 400 for missing required claim fields.
  it("Claims: create claim with missing fields returns 400", async () => {
    const email = `invalid-claim.${Date.now()}@example.com`;

    // Register and authenticate, then submit an invalid claim body.
    const registerResponse = await request(app).post("/api/auth/register").send({
      name: "Invalid Claim User",
      email,
      password: "password123"
    });

    const token = registerResponse.body.token as string;

    const response = await request(app)
      .post("/api/claims")
      .set("Authorization", `Bearer ${token}`)
      .send({
        description: "Missing policy and other fields"
      });

    expect(response.status).toBe(400);
  });
});